spring.application.name=DuAnTotNghiep_Nhom2
server.port=8080

# Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=FootballRentalDB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.thymeleaf.cache=false
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=WARN

# ================= VNPAY CONFIG (SANDBOX) =================
# B?n hãy thay th? 2 dòng d??i b?ng thông tin th?t trong email c?a b?n
vnpay.tmn_code=T5C98VKZ
vnpay.hash_secret=GMJJ31XC5E4DLE7EGUPP410UEUMKL93S

vnpay.url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return_url=http://localhost:8080/payment/vnpay-return
